### ISSUE TITLE
Public repos have issue templates

### ISSUE THREAD

**Issue by izgeri** [cyberark/community#26]
All public repos have bug and feature request issue templates.

Suggested templates:
- [Bug template](https://github.com/conjurinc/docs/blob/master/templates/issues/bug.md)
- [Feature request template](https://github.com/conjurinc/docs/blob/master/templates/issues/feature-request.md)

Repos:
- [ ] conjurinc/appliance-docker-ami
- [x] cyberark/bash-lib#21
- [x] cyberark/conjur-aws#20
- [x] cyberark/homebrew-tools#9
- [ ] conjurdemos/cloudfoundry-conjur-demo#53
- [ ] conjurdemos/kubernetes-conjur-demo#87
- [x] conjurdemos/pet-store-demo#21
- [x] cyberark/ansible-conjur-host-identity#24
- [x] cyberark/cloudfoundry-conjur-buildpack#54
- [x] cyberark/conjur-puppet#56
- [x] cyberark/conjur-service-broker#145
- [x] cyberark/sidecar-injector#12
- [x] cyberark/terraform-provider-conjur#38
- [ ] conjurinc/tenfactorci
- [x] cyberark/dev-flow
- [x] cyberark/parse-a-changelog#12
- [ ] conjurdemos/conjur-intro
- [x] cyberark/conjur-quickstart
- [ ] ~cyberark/go-mssqldb~
- [x] cyberark/secretless-broker
- [ ] conjurinc/summon-conjurcli#4
- [x] cyberark/summon#127
- [x] cyberark/summon-aws-secrets#23
- [x] cyberark/summon-chefapi#7
- [x] cyberark/summon-conjur#48
- [x] cyberark/summon-file#4
- [x] cyberark/summon-keyring#10
- [x] cyberark/summon-s3#10
- [x] cyberark/community#25
- [x] cyberark/conjur-oss-suite-release#32
- [x] cyberark/secrets-provider-for-k8s#66
- [x] cyberark/conjur-authn-k8s-client#81

**Comment by sgnn7** [comment]
# Current state (Mar 10)

## Completed

- [x] conjurinc/appliance-docker-ami
- [x] cyberark/bash-lib
- [x] conjurdemos/cloudfoundry-conjur-demo
- [x] conjurdemos/kubernetes-conjur-demo
- [x] conjurdemos/pet-store-demo
- [x] cyberark/ansible-conjur-host-identity
- [x] cyberark/cloudfoundry-conjur-buildpack
- [x] cyberark/conjur-puppet
- [x] cyberark/conjur-service-broker
- [x] cyberark/sidecar-injector
- [x] cyberark/terraform-provider-conjur
- [x] cyberark/conjur-quickstart
- [x] cyberark/secretless-broker
- [x] cyberark/summon
- [x] cyberark/summon-aws-secrets
- [x] cyberark/summon-chefapi
- [x] cyberark/summon-file
- [x] cyberark/summon-keyring
- [x] cyberark/summon-s3
- [x] cyberark/community
- [x] cyberark/conjur-oss-suite-release
- [x] cyberark/secrets-provider-for-k8s

## Not completed

- [ ] cyberark/conjur-aws#22 - **Broken build prevents merge**
- [ ] cyberark/homebrew-tools#10 - **Bad revert in history**
- [ ] conjurinc/tenfactorci - **No PR**
- [ ] cyberark/dev-flow#68 - **Bad revert in history**
- [ ] cyberark/parse-a-changelog - **No PR**
- [ ] conjurdemos/conjur-intro - **Outdated version of feature request ([link](https://github.com/conjurdemos/conjur-intro/blob/master/.github/ISSUE_TEMPLATE/feature_request.md))** 
- [ ] conjurinc/summon-conjurcli#5 - **Bad formatting**
- [ ] cyberark/summon-conjur#49 - **Wrong label(s)**
- [ ] cyberark/conjur-authn-k8s-client#90 - **Wrong label(s)**

CC: @JakeQuilty

**Comment by JakeQuilty** [comment]
https://github.com/cyberark/parse-a-changelog/pull/18

**Comment by JakeQuilty** [comment]
Was told not to make one for conjurinc/tenfactorci

**Comment by sgnn7** [comment]
# Cont'd

## Completed
- [x] cyberark/homebrew-tools
- [x] cyberark/dev-flow
- [x] cyberark/parse-a-changelog
- [x] conjurinc/summon-conjurcli
- [x] cyberark/summon-conjur
- [x] cyberark/conjur-authn-k8s-client
- [x] conjurinc/tenfactorci - **No PR needed**

## Not completed

- [ ] cyberark/conjur-aws#22 - **Broken build prevents merge** @izgeri Not sure what you would like to do with this repo's change.
- [ ] conjurdemos/conjur-intro#54 - **PR has conflicts**

CC: @JakeQuilty
