### ISSUE TITLE
Conjur open source projects have up-to-date naming for Conjur editions

### ISSUE THREAD

**Issue by izgeri** [cyberark/community#92]
## Information

Conjur editions are being renamed so that "Conjur OSS" will be called "Conjur Open Source" everywhere and "Dynamic Access Provider" or "DAP" is called "Conjur Enterprise".

To support this, we need to update the open source suite to reflect the new names.

In particular:
- When you see `Conjur OSS` it should become `Conjur Open Source`
- When you see `DAP` it should become `Conjur Enterprise`
   - If the system requirements says "DAP v10+" they should be updated to "Conjur Enterprise (formerly DAP) v10+"
- When you see `Dynamic Access Provider` it should become `Conjur Enterprise`

We **do not** need to change `Conjur OSS Suite` OR `Conjur Open Source Suite`.

When relevant, we need to ensure the update will propagate to where artifacts are published _on the next release_ (e.g. for Ansible, PCF, RedHat). We **do not** need to release as part of this card.  We also need to update GitHub pages (Summon, Secretless, Conjur Landing page). The full list is below.

_Out of scope_: Concourse

If possible and easy, we should automate this (in particular for the README / CONTRIB updates):
- Use the tool that infra recommends to mass clone repos
- Use the GitHub CLI to iterate through the projects, and in each:
  - Create a branch
  - Search and replace
  - Commit & push
  - Open a PR
- Share any code snippets or scripts you use in the process by adding them to `conjurinc/docs` for future reference.

### Projects (READMEs / CONTRIBUTING files)

- [x] cyberark/conjur
- [x] cyberark/conjur-openapi-spec
- [x] cyberark/conjur-oss-helm-chart
- [x] cyberark/conjur-cli
- [x] cyberark/conjur-api-dotnet
- [x] cyberark/conjur-api-go
- [x] cyberark/conjur-api-java
- [x] cyberark/conjur-api-python3
- [x] cyberark/conjur-api-ruby
- [x] cyberark/conjur-sdk-java
- [x] cyberark/cloudfoundry-conjur-buildpack
- [x] cyberark/conjur-service-broker
- [x] cyberark/conjur-authn-k8s-client
- [x] cyberark/secrets-provider-for-k8s
- [x] cyberark/ansible-conjur-collection
- [x] cyberark/ansible-conjur-host-identity
- [x] cyberark/conjur-puppet
- [x] cyberark/terraform-provider-conjur
- [x] cyberark/secretless-broker
- [x] cyberark/summon
- [x] cyberark/summon-conjur
- [x] cyberark/summon-aws-secrets
- [x] cyberark/summon-s3
- [x] cyberark/summon-chefapi
- [x] cyberark/summon-keyring
- [x] cyberark/bash-lib
- [x] cyberark/helm-charts
- [x] cyberark/homebrew-tools
- [x] cyberark/parse-a-changelog
- [x] conjurdemos/pet-store-demo
- [x] conjurdemos/cloudfoundry-conjur-demo
- [x] conjurinc/cloudfoundry-conjur-tile
- [x] cyberark/conjur-base-image
- [x] cyberark/conjur-credentials-plugin
- [x] cyberark/conjur-oss-suite-release
- [x] cyberark/conjur-quickstart
- [x] cyberark/conjur-template
- [x] cyberark/community
- [x] cyberark/go-mssqldb
- [x] cyberark/katacoda-scenarios
- [x] conjurdemos/kubernetes-conjur-demo
- [x] cyberark/kubernetes-conjur-deploy
- [x] cyberark/sidecar-injector

### GitHub pages / R&D owned docs
- [x] cyberark/docs-cyberark-conjur-service-broker
- [x] cyberark/conjur ([/docs folder](https://github.com/cyberark/conjur/tree/master/docs))
- [x] cyberark/summon ([/docs folder](https://github.com/cyberark/summon/tree/master/docs))
- [x] cyberark/secretless-broker ([/docs folder](https://github.com/cyberark/secretless-broker/tree/master/docs))

## Acceptance criteria

- [x] Send infra a list of DockerHub / Red Hat container registry documentation that needs to be updated
- [x] Update all README / CONTRIBUTING files in the listed projects below to have updated names
- [x] Update all listed GitHub pages / R&D owned docs listed below

**Comment by izgeri** [comment]
@izgeri please add project list

**Comment by john-odonnell** [comment]
**Open PRs**
- [ ] [cyberark/conjur-api-dotnet#75](https://github.com/cyberark/conjur-api-dotnet/pull/75)
- [ ] [cyberark/conjur-api-go#112](https://github.com/cyberark/conjur-api-go/pull/112)
- [ ] [cyberark/conjur-api-java#104](https://github.com/cyberark/conjur-api-java/pull/104)
- [ ] [cyberark/conjur-api-ruby#194](https://github.com/cyberark/conjur-api-ruby/pull/194)
- [x] [cyberark/conjur-api-python3#308](https://github.com/cyberark/conjur-api-python3/pull/308)
- [ ] [cyberark/conjur-authn-k8s-client#335](https://github.com/cyberark/conjur-authn-k8s-client/pull/335)
- [ ] [cyberark/conjur-cli#315](https://github.com/cyberark/conjur-cli/pull/315)
- [ ] [cyberark/conjur-openapi-spec#199](https://github.com/cyberark/conjur-openapi-spec/pull/199)
- [ ] [cyberark/conjur-oss-helm-chart#151](https://github.com/cyberark/conjur-oss-helm-chart/pull/151)
- [ ] [cyberark/conjur-sdk-java#49](https://github.com/cyberark/conjur-sdk-java/pull/49)
- [ ] [cyberark/secrets-provider-for-k8s#331](https://github.com/cyberark/secrets-provider-for-k8s/pull/331)

**No PR Needed**
- cyberark/cloudfoundry-conjur-buildpack
- cyberark/conjur-service-broker

**Comment by jtuttle** [comment]
All PRs reviewed and merged. Thanks @john-odonnell !
